### ISSUE TITLE
jaguar_orm RangeError: Invalid value: Not in range 0..1114111, inclusive: -1

### ISSUE THREAD

**Issue by zhaochh75** [Jaguar-dart/jaguar_orm#192]
jaguar_orm                                              RangeError: Invalid value: Not in range 0..1114111, inclusive: -1
it's a breaking change in dart 2.8. downgrade to dart 2.7

----------------------------------------------------------------------------------
await userBean.createTable ();

Error rangeerror: invalid value: not in range 0.. 1114111, inclusive: - 1

I found that dart SDK 2.8 is too high, and it has been downgraded to 2.7

Hope to match the higher version of dart.

https://stackoverflow.com/questions/61534696/rangeerror-invalid-value-not-in-range-0-1114111-inclusive-1-when-trying-to

**Comment by RandyWei** [comment]
same for me!

`
Dart SDK version: 2.10.4 (stable) (Wed Nov 11 13:35:58 2020 +0100) on "macos_x64"
`
`
Unhandled exception:
RangeError: Invalid value: Not in inclusive range 0..1114111: -1
#0      StringBuffer.writeCharCode (dart:core-patch/string_buffer_patch.dart:74:9)
#1      PostgreSQLFormat.substitute (package:postgres/src/substituter.dart:83:29)
#2      Query.sendSimple (package:postgres/src/query.dart:45:38)
#3      _PostgreSQLConnectionStateIdle.processQuery (package:postgres/src/connection_fsm.dart:177:11)
#4      _PostgreSQLConnectionStateIdle.awake (package:postgres/src/connection_fsm.dart:168:14)
#5      _PostgreSQLExecutionContextMixin._enqueue (package:postgres/src/connection.dart:399:67)
#6      _PostgreSQLExecutionContextMixin.execute (package:postgres/src/connection.dart:345:12)
#7      PgAdapter.createTable (package:jaguar_query_postgres/src/adapter.dart:112:23)
#8      _UserBean.createTable (package:jaguar_demo001/entity/user.jorm.dart:107:20)
#9      main (file:///Users/wei/Documents/vscode-workspace/jaguar_demo001/bin/test.dart:12:18)
<asynchronous suspension>
#10     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#11     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)`
